include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - require_trailing_commas

analyzer:
  plugins:
    - custom_lint
  errors:
    # disable invalid annotation lint for freezed with json_annotation
    invalid_annotation_target: ignore
  # ignore generated files
  exclude: [lib/**.freezed.dart, lib/**.g.dart]